#!/bin/bash

rm nvc_main.x

CXX="nvc++"

LINKFLAG="-ltensorflow -L/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/lib64 -L/usr/lib64/ -L/opt/local/lib/gcc11/"

NVCFLAG="-O3 -std=c++20 -target=gpu -Minline -fopenmp -cuda -stdpar=multicore"

$CXX $NVCFLAG $LINKFLAG -c axpy.cu

$CXX $NVCFLAG $LINKFLAG -c main.cpp

$CXX $NVCFLAG $LINKFLAG -c read_data.cpp

$CXX $NVCFLAG $LINKFLAG -c data_struct.cpp

$CXX $NVCFLAG $LINKFLAG -c VDW_Coulomb.cu

$CXX $NVCFLAG $LINKFLAG main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x

rm *.o
