#!/bin/bash

module load PrgEnv-nvhpc

rm *.o nvc_main.x

CXX="nvc++"

torchDir="/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/site-packages/torch"
# Change the following cppflow and tensorflow directory to your own ones
cppflowDir="~/ctensorflow/usr/local"   
tfDir="~/ctensorflow"

LINKFLAG="-lstdc++fs -I${cppflowDir}/include/ -I${tfDir}/include/  -ltensorflow -D_GLIBCXX_USE_CXX11_ABI=1 -L${torchDir}/lib -I${torchDir}/include/ -I${torchDir}/include/torch/csrc/api/include -Wl,-R${torchDir}/lib -ltorch -ltorch_cpu -lc10 -ltorch_cuda -L/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/cuda/lib64 -L/usr/lib64/"

NVCFLAG="-O3 -std=c++20 -Minline -mp -target=gpu -cuda"

$CXX $NVCFLAG -c axpy.cu $LINKFLAG

$CXX $NVCFLAG -c main.cpp $LINKFLAG

$CXX $NVCFLAG -c read_data.cpp $LINKFLAG

$CXX $NVCFLAG -c data_struct.cpp $LINKFLAG

$CXX $NVCFLAG -c VDW_Coulomb.cu $LINKFLAG

$CXX $NVCFLAG main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x $LINKFLAG

