#!/bin/bash

set -e

rm -f nvc_main.x *.o *.ii *.cpp.ii

CXX="$(which nvcc)"

CUDA_LIB="$(dirname "$(dirname "$(dirname "$CXX")")")/cuda/lib64"
LINKFLAG="-L${CUDA_LIB} -L/usr/lib64/ -arch=native"

NVCFLAG="-O3 -std=c++20 -x cu -expt-relaxed-constexpr -rdc=true -Xcompiler -fopenmp"

echo "=== axpy.cu ==="
$CXX $NVCFLAG $LINKFLAG -c axpy.cu -o axpy.o

echo "=== main.cpp ==="
$CXX $NVCFLAG $LINKFLAG -c main.cpp -o main.o

echo "=== read_data.cpp ==="
$CXX $NVCFLAG $LINKFLAG -c read_data.cpp -o read_data.o

echo "=== data_struct.cpp ==="
$CXX $NVCFLAG $LINKFLAG -c data_struct.cpp -o data_struct.o

echo "=== VDW_Coulomb.cu ==="
$CXX $NVCFLAG $LINKFLAG -c VDW_Coulomb.cu -o VDW_Coulomb.o

echo "=== linking ==="
$CXX -std=c++20 -rdc=true -Xcompiler -fopenmp $LINKFLAG \
    main.o \
    read_data.o \
    axpy.o \
    data_struct.o \
    VDW_Coulomb.o \
    -o nvc_main.x

echo "================================"
echo "gRASPA compilation successful!"
echo "================================"

rm -f *.o *.ii *.cpp.ii