#!/bin/bash

# Updated for NERSC's new module system (November 2024+)
# The nvhpc module is deprecated - use PrgEnv-nvidia + cuda instead
# This is the VANILLA version (no ML dependencies)

# Restore module system defaults if needed
if [ -f /opt/cray/pe/cpe/24.07/restore_lmod_system_defaults.sh ]; then
    source /opt/cray/pe/cpe/24.07/restore_lmod_system_defaults.sh
fi

module purge
module load PrgEnv-nvidia
module load cuda/12.4

rm -f *.o nvc_main.x

CXX="nvc++"

# Vanilla version - no TensorFlow/CppFlow/PyTorch needed
LINKFLAG="-lstdc++fs -L/opt/nvidia/hpc_sdk/Linux_x86_64/24.5/cuda/lib64 -L/usr/lib64/"

NVCFLAG="-O3 -std=c++20 -Minline -mp -target=gpu -cuda"

$CXX $NVCFLAG -c axpy.cu $LINKFLAG

$CXX $NVCFLAG -c main.cpp $LINKFLAG

$CXX $NVCFLAG -c read_data.cpp $LINKFLAG

$CXX $NVCFLAG -c data_struct.cpp $LINKFLAG

$CXX $NVCFLAG -c VDW_Coulomb.cu $LINKFLAG

$CXX $NVCFLAG main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x $LINKFLAG

