#!/bin/bash
runs=24
currentdir=$(pwd)

./start_as_root.sh

for ((i = 0; i < $runs; i++)); do
  echo  $i
  mkdir $i
  cp $currentdir/*.def $i/; cp $currentdir/simulation.input $i/; cp $currentdir/*.cif $i/
  cd $currentdir/$i
  sed -i 's/xxx/'$i'/g' simulation.input
  #sed -i 's/aaa/'$i'/g' simulation.input
  #sed -i 's/bbb/'$nexti'/g' simulation.input
  ../../../nvc_main.x > result &
  cd ../
done

wait

./stop_as_root.sh
