#!/bin/bash

rm nvc_main.x

CXX="nvc++"

LINKFLAG="-ltensorflow -L/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/lib64 -L/usr/lib64/ -L/opt/local/lib/gcc11/"

#NVCFLAG="-O3 -std=c++20 -gpu=cc86 -Minline -fopenmp -Minfo -DUSE_DOUBLE -cuda"
NVCFLAG="-O3 -std=c++20 -gpu=cc86 -Minline -fopenmp -cuda -stdpar=multicore"

#$CXX $NVCFLAG -c RN.cpp

#$CXX $NVCFLAG $LINKFLAG Third-cppflow.cpp -o test.x 


$CXX $NVCFLAG -c axpy.cu

$CXX $NVCFLAG -c main.cpp

$CXX $NVCFLAG -c read_data.cpp

$CXX $NVCFLAG -c data_struct.cpp

$CXX $NVCFLAG -c VDW_Coulomb.cu

#$CXX $NVCFLAG -c print_statistics.cu

$CXX $NVCFLAG $LINKFLAG main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x

rm *.o
